// AUTO-GENERATED from the actual filesystem.
// Do not edit by hand — regenerate with the Node command in README/asset notes.
export const COLLISION_SOUND_FILES = [
  "are-baap-re-yaad-aya.mp3",
  "atmkbfjg-echo.mp3",
  "chicken-on-tree-screaming.mp3",
  "chodu-cid-chut.mp3",
  "chodu-cid-teri-maiya.mp3",
  "cid-acp-behn-choo.mp3",
  "cid-chut.mp3",
  "cid-le-mdc.mp3",
  "cid-tum-bkl-f.mp3",
  "cid.mp3",
  "cidxhoneysingh-song.mp3",
  "contesta-punetas.mp3",
  "dil-na-diya.mp3",
  "du-bist-gut-genug.mp3",
  "f-you-baltimore.mp3",
  "fe-n-travis-scott.mp3",
  "gta-san-andreas-ah-shit-here-we-go-again.mp3",
  "hello-moto-estourado.mp3",
  "i-sh-t-my-pants-aldi.mp3",
  "kyu-re-madarchod-cid.mp3",
  "miguel-miguel_BwNUGvA.mp3",
  "mkb-aag-asphalt-1327-version_jDZRZ64.mp3",
  "mr-beast-phonk-meme-mp3.mp3",
  "naam-ya-daam-naam-ravi-kishan.mp3",
  "nahi-nahi-saluke-yaha-kuchh-to-gadbad-hai.mp3",
  "nikal-jao-mere-lo-e-ke-samne-se_y19lYpE.mp3",
  "oi-oi-oe-oi-a-eye-eye.mp3",
  "phir-teri-maiya-chodta-hu-cid.mp3",
  "really-nig.mp3",
  "tralalero-funk.mp3",
  "what-the-hell-omg-no-wayyyyy.mp3",
  "whoooooo-yeleeee-laudeeee_Nk6JpCP.mp3",
  "y2mate_HOnnyD0.mp3",
  "yes-yes-yes-skibidi.mp3"
];

export const BILLBOARD_IMAGE_FILES = [
  "aksh_kmr.PNG",
  "arpit_bala_1.PNG",
  "arpit_bala_2.PNG",
  "boat.PNG",
  "hakla.PNG",
  "hamza.PNG",
  "jhatura.PNG",
  "ladki1.PNG",
  "modihji.PNG",
  "modihji2.PNG",
  "robie.PNG",
  "udhar_dekh.PNG",
  "vimal_all_three.PNG",
  "vo_pakistani.PNG"
];
